### ISSUE TITLE
Add batching

### ISSUE THREAD

**Issue by Nathanwoodburn** [Nathanwoodburn/HSDBidderGUI#1]
Add batching to lower costs and increase speed.

https://discord.com/channels/822591034202521641/840994858112909403/1062983737073221652

**Comment by nglabs42** [comment]
Might need to make a couple changes doing batching, I would talk to Pinhead, I was asked to make a local change with my sendbatch testing.  Additionally, I have had issues with my wallet if I do too many opens and bids on a single wallet.  Two issues I have ran until that might impact this.
