### ISSUE TITLE
We might need to clarify how to use it.

### ISSUE THREAD

**Issue by enginux** [Nathanwoodburn/HSDBidderGUI#2]
### Some clarifications,

- use it along with Bob Desktop in SPV or HSD Full Node.
- use it along with HSD (SPV or Full Node).
- use it with your Passphrase, Wallet name and Api-Key.

Also, some features not needed is because Bob can do it especially Bulk Reveal, Redeem etc...ref: https://github.com/Nathanwoodburn/HSDBidderGUI/blob/d5f39fb1d1af2acf2aca6c949fa4471591008879/BidderGUI/Form1.cs#L156

**Comment by Nathanwoodburn** [comment]
I think it would be best to keep the REVEAL and REDEEM.
They can be used by people without Bob. Also this GUI uses batching which I don't know if Bob does. If Bob doesn't this GUI would be sending REVEALS/REDEEMS faster and cheaper.

**Comment by Nathanwoodburn** [comment]
I've updated the [Readme](https://github.com/Nathanwoodburn/HSDBidderGUI/blob/master/README.md). Let me know if I there was anything else that needed changing
